apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-bak4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qmix-tenant/rhtap-demo-app/hacbs-test-project-bak4@sha256:d3975214c1c30616651c6875621d3dc2a38c3fdafaa07cf28ed0962923e0715a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
